version: "3.8"

services:
  api:
    image: "infra-test_api"

  web:
    image: "infra-test_web"
    build:
      args:
        - REACT_APP_API_ADDRESS=http://localhost:$NGINX_LOCAL_PORT/api

  nginx:
    image: 'infra-test_nginx'
    ports:
      - "$NGINX_LOCAL_PORT:80"
  