version: "3.8"

services:
  api:
    image: "infra-test_api"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`$DOMAIN`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.api.middlewares=api-stripprefix"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=3001"
  web:
    image: "infra-test_web"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=3000"

  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "${ENTRYPOINT_PORT?}:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  postgres:
    image: 'postgres:13'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=infra_test
    ports:
      - "$POSTGRES_LOCAL_PORT:5432"