version: "3.8"

services:
  api:
    image: "jbrunton/infra-test_api:${TAG?}"
    build:
      context: ./packages/api
    ports:
      - "3001:3001"

  web:
    image: "jbrunton/infra-test_web:${TAG?}"
    build:
      context: ./packages/web
      args:
        - "REACT_APP_API_ADDRESS=${API_ADDRESS?}"
    ports:
      - "3000:3000"

  nginx:
    image: "jbrunton/infra-test_nginx:${TAG?}"
    build:
      context: ./nginx
    ports:
      - 80:80

  postgres:
    image: 'postgres:13'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=infra_test
    ports:
      - "$POSTGRES_LOCAL_PORT:5432"
