version: "3.8"

services:
  api:
    image: "jbrunton/infra-test_api:${TAG?}"
    build:
      context: ./packages/api
    environment:
      - POSTGRES_DISABLE_SSL=1


  web:
    image: "jbrunton/infra-test_web:${TAG?}"
    build:
      context: ./packages/web
    environment:
      - "REACT_APP_API_ADDRESS=$API_ADDRESS"

