version: "3.8"

services:
  api:
    image: "jbrunton/infra-test_api:${TAG?}"
    build:
      context: ./packages/api
    ports:
      - "3001:3001"

  web:
    image: "jbrunton/infra-test_web:${TAG?}"
    build:
      context: ./packages/web
    ports:
      - "3000:3000"
