services:
  api:
    version: "latest"
    instanceCount: 1
    instanceSizeSlug: basic-xxs
    jobs:
      - name: api-migrate
        kind: POST_DEPLOY
        instanceSizeSlug: basic-xxs
        runCommand: npx knex migrate:latest
  web:
    version: "latest"
    instanceCount: 1
    instanceSizeSlug: basic-xxs
jobs:
  db-migrate:
    version: latest
    instanceSizeSlug: basic-xxs
