services:
  api:
    version: "1.0"
    instanceCount: 1
    instanceSizeSlug: basic-xxs
    jobs:
      - name: api-migrate
        kind: POST_DEPLOY
        instanceSizeSlug: basic-xxs
        runCommand: npx knex migrate:latest
  web:
    version: "2.0"
    instanceCount: 1
    instanceSizeSlug: basic-xxs
