name: infra-test-staging
region: lon
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
- rule: DEPLOYMENT_LIVE
databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
domains:
- domain: staging.jbrunton-do.com
  type: PRIMARY
  zone: jbrunton-do.com
services:
- name: api
  http_port: 3001
  image:
    registry: jbrunton
    registry_type: DOCKER_HUB
    repository: infra-test_api
    tag: latest
  envs:
    - key: POSTGRES_HOST
      scope: RUN_TIME
      value: ${db.HOSTNAME}
    - key: POSTGRES_PORT
      scope: RUN_TIME
      value: ${db.PORT}
    - key: POSTGRES_USER
      scope: RUN_TIME
      value: ${db.USERNAME}
    - key: POSTGRES_PASSWORD
      scope: RUN_TIME
      value: ${db.PASSWORD}
    - key: POSTGRES_DB
      scope: RUN_TIME
      value: ${db.DATABASE}
    - key: POSTGRES_CA_CERT
      scope: RUN_TIME
      value: ${db.CA_CERT}
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
- name: web
  http_port: 3000
  image:
    registry: jbrunton
    registry_type: DOCKER_HUB
    repository: infra-test_web
    tag: simplify-entrypoint
  envs:
    - key: REACT_APP_API_ADDRESS
      scope: RUN_TIME
      value: ${APP_URL}/api
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
jobs:
- name: db-migrate
  kind: POST_DEPLOY
  image:
    registry: jbrunton
    registry_type: DOCKER_HUB
    repository: infra-test_api
    tag: latest
  run_command: npx knex migrate:latest
  envs:
    - key: POSTGRES_HOST
      scope: RUN_TIME
      value: ${db.HOSTNAME}
    - key: POSTGRES_PORT
      scope: RUN_TIME
      value: ${db.PORT}
    - key: POSTGRES_USER
      scope: RUN_TIME
      value: ${db.USERNAME}
    - key: POSTGRES_PASSWORD
      scope: RUN_TIME
      value: ${db.PASSWORD}
    - key: POSTGRES_DB
      scope: RUN_TIME
      value: ${db.DATABASE}
    - key: POSTGRES_CA_CERT
      scope: RUN_TIME
      value: ${db.CA_CERT}
  instance_count: 1
  instance_size_slug: basic-xxs
