name: build
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Docker tag name for build
        required: true
  workflow_run:
    workflows: [test]
    branches: [develop]
    types: [completed]

jobs:
  
  build:
    if: ${{ !github.event.workflow_run || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      TAG: ${{ github.event.inputs.tag && github.event.inputs.tag || 'latest' }}
    steps:
      - uses: actions/checkout@v2
      - uses: vmware-tanzu/carvel-setup-action@v1
      - name: Docker Login
        run: echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - name: Build
        run: build/build.sh
