name: deploy
on:
  workflow_dispatch:

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v2
      - name: Run deploy playbook
        run: ansible-playbook playbooks/deploy.yml -i hosts.yml
