name: deploy-dev
on:

  workflow_dispatch:
    inputs:
      stack_name:
        description: Stack to deploy to
        required: true

jobs:

  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: ./pulumi
      - id: pulumi
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ github.event.inputs.stack_name }}
          work-dir: pulumi
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
