name: deploy-staging

on:

  push:
    branches:
      - develop
    paths:    
      - config/staging.yml

  workflow_run:
    workflows: [build]
    branches: [develop]
    types: [completed]

jobs:

  deploy:
    if: ${{ !github.event.workflow_run || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: ./pulumi
      - id: pulumi
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: staging
          work-dir: pulumi
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
