name: deploy
on:

  workflow_dispatch:
    inputs:
      stack_name:
        description: Stack to deploy to
        required: true
        default: dev
      tag:
        description: Docker tag name to deploy
        required: true
        default: latest

  workflow_run:
    workflows: [build]
    branches: [develop]
    types: [completed]

jobs:

  provision:
    if: ${{ !github.event.workflow_run || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      stack_name: ${{ github.event.inputs.stack_name && github.event.inputs.stack_name || 'dev' }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: ./pulumi
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ env.stack_name }}
          work-dir: pulumi
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

  deploy:
    needs: provision
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible
    env:
      stack_name: ${{ github.event.inputs.stack_name && github.event.inputs.stack_name || 'dev' }}
      tag: ${{ github.event.inputs.tag && github.event.inputs.tag || 'latest' }}
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v2
      - name: Run deploy playbook
        run: ansible-playbook playbooks/deploy.yml -i hosts.yml --extra-vars "stack_name=${stack_name} tag=${tag}"
