name: destroy
on:
  workflow_dispatch:
    inputs:
      stack_name:
        description: Stack to destroy
        required: true

env:
  # If triggered manually, inputs.stack_name is provided. Else, triggered by push to develop.
  stack_name: ${{ github.event.inputs.stack_name && github.event.inputs.stack_name || 'dev' }}

jobs:
  
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: ./pulumi
      - uses: pulumi/actions@v3
        with:
          command: destroy
          stack-name: ${{ env.stack_name }}
          work-dir: pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
