name: destroy
on:
  workflow_dispatch:

jobs:
  
  provision:
    runs-on: ubuntu-latest
    env:
      DO_PAT: ${{ secrets.DO_PAT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v2
      - name: create ssh key
        run: |
          mkdir -p $GITHUB_WORKSPACE/.ssh/
          echo "$SSH_PRIVATE_KEY" > $GITHUB_WORKSPACE/.ssh/private.key
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.2
      - name: Init
        run: terraform init -input=false
      - name: Plan
        run: terraform destroy -input=false -var "do_token=${DO_PAT}" -var "pvt_key=$GITHUB_WORKSPACE/.ssh/private.key"
