name: test
on: [push]
jobs:
  cypress:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm ci
      - run: ./build/start-local.sh
      - name: Cypress run
        uses: cypress-io/github-action@v2
